export const REQUEST_WEATHER = 'REQUEST_WEATHER'
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER'
export const REQUEST_POLLUTION = 'REQUEST_POLLUTION'
export const RECEIVE_POLLUTION = 'RECEIVE_POLLUTION'
export const ERROR = 'ERROR';